"""Direct Postgres access, for the things PostgREST cannot do: DDL and sizes.

The REST endpoint the rest of the pipeline uses cannot run `create table` or
report how much disk a table occupies, so schema changes would otherwise be a
manual paste into the Supabase SQL editor.

Why pg8000 and not psycopg: the libpq that ships with psycopg-binary here
verifies the server certificate even under `sslmode=require`, and Supabase's
transaction pooler presents a certificate signed by Supabase's own CA rather
than a public one, so every psycopg attempt fails with "certificate verify
failed". The only psycopg mode that connected was `sslmode=allow`, which
negotiates plaintext first and would put the database password on the wire in
the clear. pg8000 is pure Python and takes an ssl.SSLContext directly, so the
connection is encrypted without demanding a CA we do not have - the same
posture as `sslmode=require`.

(`pg_stat_ssl` reports False on this connection. That is the pooler's own
backend leg to Postgres, not the client leg; pg8000 raises if the server
refuses its SSLRequest, so TLS on our side is established.)

Credentials come from PGHOST/PGPORT/PGDATABASE/PGUSER/PGPASSWORD.
"""

import logging
import os
import re
import ssl
from typing import List, Optional, Tuple

logger = logging.getLogger("mp.dbadmin")


def _ssl_context() -> ssl.SSLContext:
    ctx = ssl.create_default_context()
    # Supabase's pooler certificate is signed by a private Supabase CA. We are
    # not pinning it, so encrypt without verifying rather than fall back to a
    # plaintext connection.
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    return ctx


def missing_config() -> List[str]:
    return [v for v in ("PGHOST", "PGDATABASE", "PGUSER", "PGPASSWORD")
            if not os.environ.get(v)]


def connect(timeout: int = 30):
    import pg8000.dbapi

    missing = missing_config()
    if missing:
        raise RuntimeError("Postgres not configured, missing: " + ", ".join(missing))
    return pg8000.dbapi.connect(
        host=os.environ["PGHOST"],
        port=int(os.environ.get("PGPORT", "5432")),
        database=os.environ["PGDATABASE"],
        user=os.environ["PGUSER"],
        password=os.environ["PGPASSWORD"],
        ssl_context=_ssl_context(),
        timeout=timeout,
    )


def split_statements(sql: str) -> List[str]:
    """Split a script into statements on semicolons outside quotes/comments.

    Deliberately small: this file's SQL is generated by schema.py, so it has no
    dollar-quoted bodies or procedural blocks to worry about.
    """
    out, buf = [], []
    in_single = False
    in_line_comment = False
    i = 0
    while i < len(sql):
        ch = sql[i]
        nxt = sql[i + 1] if i + 1 < len(sql) else ""
        if in_line_comment:
            buf.append(ch)
            if ch == "\n":
                in_line_comment = False
        elif in_single:
            buf.append(ch)
            if ch == "'":
                if nxt == "'":          # escaped quote
                    buf.append(nxt)
                    i += 1
                else:
                    in_single = False
        elif ch == "-" and nxt == "-":
            in_line_comment = True
            buf.append(ch)
        elif ch == "'":
            in_single = True
            buf.append(ch)
        elif ch == ";":
            stmt = "".join(buf).strip()
            if _is_executable(stmt):
                out.append(stmt)
            buf = []
        else:
            buf.append(ch)
        i += 1
    tail = "".join(buf).strip()
    if _is_executable(tail):
        out.append(tail)
    return out


def _is_executable(stmt: str) -> bool:
    """Ignore fragments that are only comments or blank."""
    body = re.sub(r"--[^\n]*", "", stmt).strip()
    return bool(body)


def apply_sql(sql: str, stop_on_error: bool = False) -> Tuple[int, List[str]]:
    """Run every statement. Returns (applied, errors).

    Each statement is committed on its own so one failure cannot roll back the
    rest; the SQL is idempotent, so re-running after a fix is safe.
    """
    statements = split_statements(sql)
    applied, errors = 0, []
    conn = connect()
    try:
        conn.autocommit = True
        cur = conn.cursor()
        for stmt in statements:
            try:
                cur.execute(stmt)
                applied += 1
            except Exception as exc:  # noqa: BLE001
                head = " ".join(stmt.split())[:110]
                errors.append(f"{type(exc).__name__}: {str(exc)[:160]}  <<{head}>>")
                if stop_on_error:
                    break
    finally:
        conn.close()
    return applied, errors


def table_sizes(tables: Optional[List[str]] = None) -> List[tuple]:
    """(table, total_bytes, pretty, live_rows) for public tables, largest first."""
    conn = connect()
    try:
        cur = conn.cursor()
        cur.execute("""
            select c.relname,
                   pg_total_relation_size(c.oid),
                   pg_size_pretty(pg_total_relation_size(c.oid)),
                   coalesce(s.n_live_tup, 0)
            from pg_class c
            join pg_namespace n on n.oid = c.relnamespace
            left join pg_stat_user_tables s on s.relid = c.oid
            where n.nspname = 'public' and c.relkind = 'r'
            order by pg_total_relation_size(c.oid) desc
        """)
        rows = cur.fetchall()
    finally:
        conn.close()
    if tables:
        wanted = set(tables)
        rows = [r for r in rows if r[0] in wanted]
    return rows


def database_size() -> Tuple[int, str]:
    conn = connect()
    try:
        cur = conn.cursor()
        cur.execute("select pg_database_size(current_database()), "
                    "pg_size_pretty(pg_database_size(current_database()))")
        return tuple(cur.fetchone())
    finally:
        conn.close()
